export const images = {
  yourlogo: "/assets/brainwave.png",
  brainwave: "/assets/brainwave.png",
  check: "/assets/check.svg",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  brainwaveSymbol: "/assets/brainwave.png",
  brainwaveWhiteSymbol: "/assets/brainwave.png",
  play: "/assets/play.svg",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/loading.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/robot.jpg",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  figma: "/assets/collaboration/figma.png",
  framer: "/assets/collaboration/framer.png",
  notion: "/assets/collaboration/notion.png",
  photoshop: "/assets/collaboration/photoshop.png",
  protopie: "/assets/collaboration/protopie.png",
  raindrop: "/assets/collaboration/raindrop.png",
  slack: "/assets/collaboration/slack.png",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/image-1.png",
  roadmap2: "/assets/roadmap/image-2.png",
  roadmap3: "/assets/roadmap/image-3.png",
  roadmap4: "/assets/roadmap/image-4.png",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook: "/assets/socials/facebook.svg",
  instagram: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
  // NFT Images
  chris: "/assets/NFTs/chris.jpg",
  dogeGoblin: "/assets/NFTs/doge-goblin.jpg",
  theBob: "/assets/NFTs/the-bob.jpg",
  theDead: "/assets/NFTs/the-dead.jpg",
  theDon: "/assets/NFTs/the-don.jpg",
  theErik: "/assets/NFTs/the-erik.jpg",
  theFace: "/assets/NFTs/the-face.jpg",
  theGringo: "/assets/NFTs/the-gringo.jpg",
  theJoker: "/assets/NFTs/the-joker.jpg",
  thePooh: "/assets/NFTs/the-pooh.jpg",
  theVenom: "/assets/NFTs/the-venom.jpg",
  theWhistle: "/assets/NFTs/the-whisle.jpg",
};

const {
  yourlogo,
  homeSmile,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  figma,
  framer,
  notion,
  photoshop,
  protopie,
  raindrop,
  slack,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  facebook,
  instagram,
  telegram,
  twitter,
  chris,
  dogeGoblin,
  theBob,
  theDead,
  theDon,
  theErik,
  theFace,
  theGringo,
  theJoker,
  thePooh,
  theVenom,
  theWhistle,
} = images;

export const nfts = [
  {
    id: "1",
    name: "Chris",
    image: chris,
    price: "0.2 DOGE",
    owner: "Unknown",
  },
  {
    id: "2",
    name: "Doge Goblin",
    image: dogeGoblin,
    price: "1.5 DOGE",
    owner: "Meme Lord",
  },
  {
    id: "3",
    name: "The Bob",
    image: theBob,
    price: "0.8 DOGE",
    owner: "CollectorX",
  },
  {
    id: "4",
    name: "The Dead",
    image: theDead,
    price: "0.6 DOGE",
    owner: "Ghost Collector",
  },
  {
    id: "5",
    name: "The Don",
    image: theDon,
    price: "2.0 DOGE",
    owner: "Crypto Mafia",
  },
  {
    id: "6",
    name: "The Erik",
    image: theErik,
    price: "1.1 DOGE",
    owner: "Elite Holder",
  },
  {
    id: "7",
    name: "The Face",
    image: theFace,
    price: "0.5 DOGE",
    owner: "Anonymous",
  },
  {
    id: "8",
    name: "The Gringo",
    image: theGringo,
    price: "0.9 DOGE",
    owner: "Cowboy Collector",
  },
  {
    id: "9",
    name: "The Joker",
    image: theJoker,
    price: "1.3 DOGE",
    owner: "Chaos Enthusiast",
  },
  {
    id: "10",
    name: "The Pooh",
    image: thePooh,
    price: "0.7 DOGE",
    owner: "Honey Hoarder",
  },
  {
    id: "11",
    name: "The Venom",
    image: theVenom,
    price: "2.5 DOGE",
    owner: "Dark Syndicate",
  },
  {
    id: "12",
    name: "The Whistle",
    image: theWhistle,
    price: "0.4 DOGE",
    owner: "Mystery Dealer",
  },
];

export const navigation = [
  {
    id: "0",
    title: "Lore",
    url: "#features",
  },
  {
    id: "1",
    title: "Buy NFTS",
    url: "#how-to-use",
  },
  {
    id: "2",
    title: "Buy Merch",
    url: "#pricing",
  },
  {
    id: "3",
    title: "Roadmap",
    url: "#roadmap",
  },
  {
    id: "4",
    title: "connect Wallet",
    url: "#connectWallet",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "Sign in",
    url: "#login",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [yourlogo, yourlogo, yourlogo, yourlogo, yourlogo];

export const brainwaveServices = ["Photo generating", "Photo enhance", "Seamless Integration"];

export const brainwaveServicesIcons = [recording03, recording01, disc02, chromecast, sliders04];

export const roadmap = [
  {
    id: "0",
    title: "Voice-Activated NFT Search",
    text: "Implement voice recognition to allow users to search, filter, and explore NFTs using natural voice commands, making the marketplace more accessible and hands-free.",
    date: "Q2 2024",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Gamified NFT Rewards",
    text: "Introduce gamification elements such as collector badges, achievement-based NFT rewards, and leaderboard rankings to incentivize community engagement and trading activity.",
    date: "Q3 2024",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Customizable NFT Profiles",
    text: "Enable users to personalize their NFT collector profiles with avatars, themes, and customizable showcases, enhancing identity and interaction within the marketplace.",
    date: "Q3 2024",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Blockchain & API Integrations",
    text: "Expand interoperability by integrating external blockchain APIs, enabling cross-chain NFT transactions, real-time floor price tracking, and live rarity analytics.",
    date: "Q4 2024",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "Seamlessly trade, showcase, and collect NFTs with a frictionless experience designed for both newcomers and seasoned collectors.";

export const collabText1 =
  "Automate your NFT listings, transfers, and royalties with cutting-edge blockchain technology, making transactions effortless and secure.";

export const collabText2 =
  "Your NFTs are protected with top-tier encryption and decentralized security, ensuring true ownership and peace of mind.";

export const collabContent = [
  {
    id: "0",
    title: "Seamless NFT Experience",
    text: collabText,
  },
  {
    id: "1",
    title: "Smart NFT Automation",
    text: collabText1,
  },
  {
    id: "2",
    title: "Unmatched Security",
    text: collabText2,
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Figma",
    icon: figma,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "Notion",
    icon: notion,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Discord",
    icon: discord,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "Slack",
    icon: slack,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "Photoshop",
    icon: photoshop,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "Protopie",
    icon: protopie,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Framer",
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "Raindrop",
    icon: raindrop,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Explorer",
    description: "Start your NFT journey with essential tools",
    price: "0",
    features: [
      "Access to the NFT marketplace",
      "Browse and explore all available NFTs",
      "Basic trading tools for buying and selling",
      "Limited free NFT drops (occasional events)",
    ],
  },
  {
    id: "1",
    title: "Collector",
    description: "Enhanced NFT trading experience with exclusive perks",
    price: "19.99",
    features: [
      "All Explorer features",
      "Lower marketplace transaction fees",
      "Exclusive early access to limited NFT drops",
      "Advanced trading insights and portfolio tracking",
      "Priority support for marketplace issues",
    ],
  },
  {
    id: "2",
    title: "Whale",
    description: "Ultimate NFT access with VIP benefits",
    price: "99.99",
    features: [
      "All Collector features",
      "Zero transaction fees on purchases",
      "VIP access to high-value NFT auctions",
      "Exclusive access to private NFT sales & whitelist spots",
      "Dedicated account manager & personal NFT advisory",
      "Guaranteed spots in NFT launchpad projects",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "The Lore of the Goblins of Doge Town.",
    text: "Long ago, before the rivers ran straight and the moons hung low, there was a scrappy little patch of earth where the wind smelled of wet fur and ambition. This was Doge Town—not a town of dogs, mind you, but...",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "The Founding of Doge Town",
    text: "The goblins set to work with reckless glee, building their town from whatever they could scavenge: bent spoons, wagon wheels, the bones of unlucky travelers, and a frankly alarming number of chewed-up boots. At the center of it all stood...",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "The Goblin Clans",
    text: "Over time, the goblins split into rival clans, each claiming to serve the Great Doge in their own ridiculous way:The Woofblades: Sneaky cutthroats...",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "The Goblins Today",
    text: "For now, the goblins of Doge Town carry on, oblivious or defiant. They bicker over who gets the shiniest Doge Coin,...",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook,
    url: "#",
  },
];
